os:
  - linux

dist: bionic

addons:
  apt:
    packages:
      - pandoc
  snaps:
    # Install as apt once we can use Ubuntu focal LTS 20.04
    # https://packages.ubuntu.com/disco/universal-ctags
    - universal-ctags

language: go

go:
  - 1.13.x

env:
  # universal-ctags should be available as "ctags" but does not seem to work.
  REQTRAQ_CTAGS=universal-ctags

script:
  - go test
  # test that formatting is consistent with gofmt
  - gofmt -l . | tee /dev/tty | if [ $(wc -l) -eq 0 ]; then exit 0; else echo 'you must run "gofmt -l -w -s" before commiting'; exit 1; fi
