os:
  - linux

addons:
  apt_packages:
    - pandoc

language: go

go:
  - 1.8.x

script:
  - go test
  # test that formatting is consistent with gofmt
  - gofmt -l . | tee /dev/tty | if [ $(wc -l) -eq 0 ]; then exit 0; else echo 'you must run "gofmt -l -w -s" before commiting'; exit 1; fi
