name: reqtraq

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17' # The Go version to download (if necessary) and use.
    - run: sudo apt install -y universal-ctags pandoc
    - run: mkdir .tools && wget https://github.com/daedaleanai/llvm-project/releases/download/ddln-llvm14-rc/llvm-14.0.0.tar.gz && tar -xf llvm-14.0.0.tar.gz -C .tools
    - run: go test -v ./...
      env:
        CGO_LDFLAGS: -L${{ github.workspace }}/.tools/llvm/lib -Wl,-rpath=${{ github.workspace }}/.tools/llvm/lib

  fmt:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17' # The Go version to download (if necessary) and use.
    - run: sudo apt install -y universal-ctags pandoc
    - run: test -z $(gofmt -l .)

  validate:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17' # The Go version to download (if necessary) and use.
    - run: sudo apt install -y universal-ctags pandoc
    - run: mkdir .tools && wget https://github.com/daedaleanai/llvm-project/releases/download/ddln-llvm14-rc/llvm-14.0.0.tar.gz && tar -xf llvm-14.0.0.tar.gz -C .tools
    - run: go run . validate --strict
      env:
        CGO_LDFLAGS: -L${{ github.workspace }}/.tools/llvm/lib -Wl,-rpath=${{ github.workspace }}/.tools/llvm/lib
